language: python

python:
    - "2.7"
    - "3.5"

addons:
  apt:
    packages:
    - libncurses5-dev
    - libncursesw5-dev
    - build-essential
    - pkg-config
    - zlib1g-dev
    - bzip2

install:
    - curl -fksSL https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2 | tar xj
    - cd samtools-1.3.1 && ./configure --prefix=$PWD 
    - make all all-htslib && make install install-htslib
    - export PATH=$PATH:$PWD/bin/

script:
  - bash ci/run.sh
